/**
 * companion — memory store
 * SQLite-backed log of activity + daily summaries
 * intentionally simple — no ORM, direct SQL
 *
 * used from the Tauri Rust backend via invoke(), or from Node if running standalone
 */

// ── schema ──────────────────────────────────────────────────────────────────
export const SCHEMA = `
  CREATE TABLE IF NOT EXISTS activity_log (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    ts         INTEGER NOT NULL,
    event_type TEXT    NOT NULL,
    value      TEXT,
    app        TEXT
  );

  CREATE TABLE IF NOT EXISTS daily_summary (
    date       TEXT PRIMARY KEY,
    summary    TEXT NOT NULL,
    mood       TEXT,
    created_at INTEGER
  );

  CREATE TABLE IF NOT EXISTS preferences (
    key   TEXT PRIMARY KEY,
    value TEXT
  );

  CREATE TABLE IF NOT EXISTS reminders (
    id        INTEGER PRIMARY KEY AUTOINCREMENT,
    message   TEXT NOT NULL,
    fire_at   INTEGER NOT NULL,
    repeat_ms INTEGER,
    fired     INTEGER DEFAULT 0
  );
`;

// ── helper: called from renderer via Tauri invoke ────────────────────────────
// On the Tauri Rust side, expose these as commands.
// Here we define the JS-side interface for the renderer.

export const memory = {
  /**
   * log a raw activity event
   * @param {string} eventType
   * @param {string|null} value
   * @param {string|null} app  active window title if available
   */
  async log(eventType, value = null, app = null) {
    if (window.__TAURI__) {
      await window.__TAURI__.invoke('db_log_event', {
        eventType, value, app, ts: Date.now()
      });
    }
  },

  /**
   * get activity counts for a given day (YYYY-MM-DD)
   */
  async getDayStats(date) {
    if (!window.__TAURI__) return null;
    return window.__TAURI__.invoke('db_get_day_stats', { date });
  },

  /**
   * save or update a daily summary (generated by AI or rule-based)
   */
  async saveSummary(date, summary, mood = null) {
    if (!window.__TAURI__) return;
    return window.__TAURI__.invoke('db_save_summary', {
      date, summary, mood, createdAt: Date.now()
    });
  },

  /**
   * get the last N daily summaries for context
   */
  async getRecentSummaries(n = 7) {
    if (!window.__TAURI__) return [];
    return window.__TAURI__.invoke('db_get_recent_summaries', { n });
  },

  /**
   * set a preference value
   */
  async setPref(key, value) {
    if (!window.__TAURI__) {
      localStorage.setItem(`companion_pref_${key}`, JSON.stringify(value));
      return;
    }
    return window.__TAURI__.invoke('db_set_pref', { key, value: JSON.stringify(value) });
  },

  /**
   * get a preference value
   */
  async getPref(key, fallback = null) {
    if (!window.__TAURI__) {
      const v = localStorage.getItem(`companion_pref_${key}`);
      return v ? JSON.parse(v) : fallback;
    }
    const v = await window.__TAURI__.invoke('db_get_pref', { key });
    return v ? JSON.parse(v) : fallback;
  },

  /**
   * schedule a reminder
   */
  async addReminder(message, fireAt, repeatMs = null) {
    if (!window.__TAURI__) return;
    return window.__TAURI__.invoke('db_add_reminder', { message, fireAt, repeatMs });
  },

  /**
   * get pending reminders
   */
  async getPendingReminders() {
    if (!window.__TAURI__) return [];
    return window.__TAURI__.invoke('db_get_pending_reminders', { now: Date.now() });
  },
};
